---

- name: Add repository
  yum_repository:
    name: httpd custom
    description: HTTPD repo
    baseurl: http://18.218.220.34/centos_repository/5/x86_64/

- name: Install HTTPD
  yum:
    name: httpd
    state: installed
